# clusters:
#   - name: cluster1
#     description: "Cluster 1"
#     imageName: ghcr.io/cloudnative-pg/postgresql:15.1
#     instances: 3
#     startDelay: 10
#     stopDelay: 10
#     primaryUpdateStrategy: unsupervised
#     bootstrap:
#       initdb:
#         database: postgres
#         owner: app
#         secret:
#           name: cluster-example-app-user
#     superuserSecret:
#       name: cluster-example-superuser
#     size: "1Gi"
#     enablePodMonitor: true
# generatorClusters:
#   - name: cluster1
#   - name: cluster2
#   - name: cluster3
#   - name: cluster4
