{{- range $index, $cluster := .Values.generatorClusters}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$cluster.name}}
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/azaurus1/gitops-pgclusters
    targetRevision: HEAD
    path: pg-clusters/{{$cluster.name}}/cluster.yaml
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
{{- end }}