{{- range $index, $cluster := .Values.generatorClusters}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{$cluster.name}}
  namespace: default
spec:
  generators:
  - git:
      repoURL: https://github.com/azaurus1/gitops-pgclusters
      revision: HEAD
      files:
      - path: pg-clusters/{{$cluster.name}}/cluster.yaml
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/azaurus1/gitops-pgclusters
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        name: in-cluster
        namespace: default #'{{`{{path.basename}}`}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
{{- end }}